#!/bin/bash -l

# Launch FVWM
FVWM_ASSETS_ROOT="${ROOT}/bc_fvwm_assets/template"
FVWM_ROOT="${FVWM_ASSETS_ROOT}" "${FVWM_ASSETS_ROOT}/fvwm_wrapper" -f "${ROOT}/fvwm/fvwmrc" &

# Load the Paraview module
module load ${PARAVIEW_MODULE}

# Set working directory to home directory
cd "${HOME}"

#
# Start Paraview
#

module load virtualgl
vglrun paraview

# Kill vncserver when user closes GUI
vncserver -kill ${DISPLAY}
