#!/bin/bash -l

# Set working directory to home directory
cd "${HOME}"

# Restore the module environment to avoid conflicts
module restore

# Launch Fluxbox
FLUXBOX_RC_FILE="${PBS_O_WORKDIR}/${PBS_JOBID}.rc"
FLUXBOX_ASSETS_ROOT="${ROOT}/fluxbox"
cat > "${FLUXBOX_RC_FILE}" << EOT
session.screen0.toolbar.widthPercent: 60
session.menuFile: $FLUXBOX_ASSETS_ROOT/menu
session.keyFile: $FLUXBOX_ASSETS_ROOT/keys
EOT
DISPLAY=${DISPLAY}.0 fluxbox -rc "${FLUXBOX_RC_FILE}" &

# Load the Paraview module
module load ${PARAVIEW_MODULE}

#
# Start Paraview
#

module load virtualgl
if [[ ${INPUT_FILE} ]]; then
  vglrun paraview --data=${INPUT_FILE}
else
  vglrun paraview
fi

# Kill vncserver when user closes GUI
vncserver -kill ${DISPLAY}
